"""
This is the pipeline for producing torque data and analyzing it.
This script builds a 4 layer network with a variable number of middle layer neurons.

The basic pipeline proceeds as follows:
    1. Data is generated by moco_script_torque_endpoint.py
        This returns two folders with several torques and paths.
        This can be optional if you already have data. Simulations take a very long time to run.
    2. Data is passed into and organized by organizeCSV.py
        This returns a csv with merged torque and kinematic data.
    3. The csv is passed into makeDataFromCSV.py   
        This returns the activity of the neural network.
    4. Take this end result over to MATLAB.
"""

import moco_script_torque_endpoint as sim
import organizeCSV as OC
import makeDataFromCSV_add_sub as makeCSV
from string import ascii_lowercase

# CHANGE:
outPath = "SimResults/" 
locStr = 'merged_data.csv'
type = 1;

# Uncomment to simulate:
sim.simulateMotion(type = 1, nbr_targets = 8, outPath = outPath, intervals= 60)

OC.organize(outPath + "torque_solutions",outPath + "path_solutions", csvName= outPath + locStr)

trials = 10
amt = [-50, -25, 0, 25, 50]
for i in amt:
    for j in range(trials):
        outStr = outPath + str(numLayers) + 'layerOutput' + ascii_lowercase[j]
        makeCSV.trainFromCSV(locStr,outStr,i)
